name: CI

env:
  HUGO_ENV: production
  NOTION_INTEGRATION_KEY: ${{ secrets.NOTION_INTEGRATION_KEY }}
  NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 */24 * * *'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 45

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install Notion scrape dependencies
        working-directory: notion
        run: npm ci
      - name: Fetch and convert Notion posts
        working-directory: notion
        run: node index.js
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
          extended: true

      - name: Build Hugo static site
        run: hugo --config config.toml,config.production.toml -D --minify

      - name: Deploy static site using FTP
        # You may pin to the exact commit or the version.
        # uses: sebastianpopp/ftp-action@eb75c5cb29d23ee4a729720a27dfb66403cb0f6d
        uses: sebastianpopp/ftp-action@v2.0.0
        with:
          # FTP host
          host: ${{ secrets.FtpHost }}
          # FTP user
          user: ${{ secrets.FtpUser }}
          # FTP password
          password: ${{ secrets.FtpPassword }}
          # Force SSL encryption
          forceSsl: true
          # Local directory
          localDir: public
          # Remote directory
          remoteDir: ${{ secrets.FtpRemoteDir }}
